name: scout-audit
on:
  pull_request:
    branches:
      - main

jobs:
  scout-audit:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      repository-projects: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Run scout
        id: scout
        uses: ./.github/actions
        with:
          working_directory: .
          fail_on_error: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cat report
        run: |
          cat ${{ steps.scout.outputs.report }}
